export enum HttpStatusCode {
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NO_CONTENT = 204,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  CONFLICT = 409,
  UNPROCESSABLE_ENTITY = 422,
  TOO_MANY_REQUESTS = 429,
  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504
}

export enum AuthStatusCode {
  COMPANY_LOGIN_SUCCESS = HttpStatusCode.OK,
  COMPANY_REGISTRATION_SUCCESS = HttpStatusCode.CREATED,
  COMPANY_LOGOUT_SUCCESS = HttpStatusCode.OK,
  
  INVALID_CREDENTIALS = HttpStatusCode.UNAUTHORIZED,
  COMPANY_NOT_AUTHENTICATED = HttpStatusCode.UNAUTHORIZED,
  ADMIN_NOT_AUTHENTICATED = HttpStatusCode.UNAUTHORIZED,
  
  COMPANY_BLOCKED = HttpStatusCode.FORBIDDEN,
  COMPANY_NOT_VERIFIED = HttpStatusCode.FORBIDDEN,
  
  EMAIL_ALREADY_EXISTS = HttpStatusCode.CONFLICT
}

export enum OTPStatusCode {
  OTP_GENERATED = HttpStatusCode.OK,
  OTP_VERIFIED = HttpStatusCode.OK,
  OTP_RESENT = HttpStatusCode.OK,
  
  OTP_INVALID = HttpStatusCode.BAD_REQUEST,
  OTP_EXPIRED = HttpStatusCode.BAD_REQUEST,
  EMAIL_REQUIRED = HttpStatusCode.BAD_REQUEST,
  OTP_REQUIRED = HttpStatusCode.BAD_REQUEST
}

export enum CompanyStatusCode {
  COMPANY_PROFILE_UPDATED = HttpStatusCode.OK,
  STEP2_COMPLETED = HttpStatusCode.OK,
  STEP3_COMPLETED = HttpStatusCode.OK,
  PROFILE_RETRIEVED = HttpStatusCode.OK,
  
  COMPANY_APPROVED = HttpStatusCode.OK,
  COMPANY_REJECTED = HttpStatusCode.OK,
  COMPANY_BLOCKED = HttpStatusCode.OK,
  COMPANY_UNBLOCKED = HttpStatusCode.OK,
  
  COMPANY_NOT_FOUND = HttpStatusCode.NOT_FOUND,
  COMPANIES_RETRIEVED = HttpStatusCode.OK,
  PENDING_COMPANIES_RETRIEVED = HttpStatusCode.OK
}

export enum ValidationStatusCode {
  VALIDATION_ERROR = HttpStatusCode.BAD_REQUEST,
  MISSING_REQUIRED_FIELDS = HttpStatusCode.BAD_REQUEST,
  REJECTION_REASON_REQUIRED = HttpStatusCode.BAD_REQUEST,
  INVALID_EMAIL_FORMAT = HttpStatusCode.UNPROCESSABLE_ENTITY,
  FIELD_TOO_LONG = HttpStatusCode.UNPROCESSABLE_ENTITY
}
